---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: upvote-app
spec:
  selector:
    matchLabels:
      app: upvote-app
      role: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: upvote-app
        role: frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/PROJECT_ID/{_REPOSITORY}/{_SERVICE_NAME}:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - name: frontend
          containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: upvote-app
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: upvote-app
    role: frontend